/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AsideGItem: typeof import('./src/components/layout/aside-gItem.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    LayoutAside: typeof import('./src/components/layout/layout-aside.vue')['default']
    LayoutHeader: typeof import('./src/components/layout/layout-header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
